name: Export GitHub Security Alerts

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/security-export@main
        id: export
        with:
          github-token: ${{ secrets.PAT }}
          repository: aaquibuddin888/juice-shop

      - uses: austenstone/json-to-csv@main
        with:
          json-artifact-name: ${{ steps.export.outputs.artifact-name }}
          create-artifact: true
          artifact-name: "GitHub Security Alerts CSV"
